FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir \
        torch \
        pillow \
        supervision \
        rfdetr \
        opencv-python-headless

# Patched RF-DETR file
COPY detr.py /opt/conda/lib/python3.11/site-packages/rfdetr/

ENV PYTHONUNBUFFERED=1 \
    PYTHONOPTIMIZE=1